// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: coordinator.proto

#include "coordinator.pb.h"
#include "coordinator.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace coordinator {

static const char* CoordinatorService_method_names[] = {
  "/coordinator.CoordinatorService/setplacementpolicy",
};

std::unique_ptr< CoordinatorService::Stub> CoordinatorService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< CoordinatorService::Stub> stub(new CoordinatorService::Stub(channel));
  return stub;
}

CoordinatorService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_setplacementpolicy_(CoordinatorService_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status CoordinatorService::Stub::setplacementpolicy(::grpc::ClientContext* context, const ::coordinator::SetPlacementCommand& request, ::coordinator::RequestResult* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_setplacementpolicy_, context, request, response);
}

void CoordinatorService::Stub::experimental_async::setplacementpolicy(::grpc::ClientContext* context, const ::coordinator::SetPlacementCommand* request, ::coordinator::RequestResult* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_setplacementpolicy_, context, request, response, std::move(f));
}

void CoordinatorService::Stub::experimental_async::setplacementpolicy(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::coordinator::RequestResult* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_setplacementpolicy_, context, request, response, std::move(f));
}

void CoordinatorService::Stub::experimental_async::setplacementpolicy(::grpc::ClientContext* context, const ::coordinator::SetPlacementCommand* request, ::coordinator::RequestResult* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_setplacementpolicy_, context, request, response, reactor);
}

void CoordinatorService::Stub::experimental_async::setplacementpolicy(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::coordinator::RequestResult* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_setplacementpolicy_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::coordinator::RequestResult>* CoordinatorService::Stub::AsyncsetplacementpolicyRaw(::grpc::ClientContext* context, const ::coordinator::SetPlacementCommand& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::coordinator::RequestResult>::Create(channel_.get(), cq, rpcmethod_setplacementpolicy_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::coordinator::RequestResult>* CoordinatorService::Stub::PrepareAsyncsetplacementpolicyRaw(::grpc::ClientContext* context, const ::coordinator::SetPlacementCommand& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::coordinator::RequestResult>::Create(channel_.get(), cq, rpcmethod_setplacementpolicy_, context, request, false);
}

CoordinatorService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      CoordinatorService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< CoordinatorService::Service, ::coordinator::SetPlacementCommand, ::coordinator::RequestResult>(
          std::mem_fn(&CoordinatorService::Service::setplacementpolicy), this)));
}

CoordinatorService::Service::~Service() {
}

::grpc::Status CoordinatorService::Service::setplacementpolicy(::grpc::ServerContext* context, const ::coordinator::SetPlacementCommand* request, ::coordinator::RequestResult* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


std::unique_ptr< FromDataNode::Stub> FromDataNode::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< FromDataNode::Stub> stub(new FromDataNode::Stub(channel));
  return stub;
}

FromDataNode::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel){}

FromDataNode::Service::Service() {
}

FromDataNode::Service::~Service() {
}


}  // namespace coordinator

